package com.tieto.p8.subvention.filenet.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-25T12:36:28.221+01:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "SubventionService",
                  wsdlLocation = "file:subventionService.wsdl",
                  targetNamespace = "http://service.filenet.subvention.p8.tieto.com")
public class SubventionService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.filenet.subvention.p8.tieto.com", "SubventionService");
    public final static QName SubventionServicePort = new QName("http://service.filenet.subvention.p8.tieto.com", "SubventionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:subventionService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SubventionService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:subventionService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SubventionService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SubventionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubventionService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SubventionService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SubventionService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SubventionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SubventionService
     */
    @WebEndpoint(name = "SubventionServicePort")
    public SubventionService getSubventionServicePort() {
        return super.getPort(SubventionServicePort, SubventionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubventionService
     */
    @WebEndpoint(name = "SubventionServicePort")
    public SubventionService getSubventionServicePort(WebServiceFeature... features) {
        return super.getPort(SubventionServicePort, SubventionService.class, features);
    }

}
