package com.tieto.p8.subvention.filenet.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-25T12:36:28.218+01:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://service.filenet.subvention.p8.tieto.com", name = "SubventionService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SubventionService {

    @WebMethod
    @WebResult(name = "ContactInformationDTO", targetNamespace = "http://service.filenet.subvention.p8.tieto.com", partName = "ContactInformationDTO")
    public ContactInformationDTO getApplicant(

        @WebParam(partName = "ytunnus", name = "ytunnus")
        java.lang.String ytunnus,
        @WebParam(partName = "reknro", name = "reknro")
        java.lang.String reknro,
        @WebParam(partName = "hetu", name = "hetu")
        java.lang.String hetu
    );

    @WebMethod
    @WebResult(name = "ResultOfService", targetNamespace = "http://service.filenet.subvention.p8.tieto.com", partName = "ResultOfService")
    public ResultOfService saveApplication(

        @WebParam(partName = "subventionApplicantAndApplication", name = "subventionApplicantAndApplication")
        Subvention subventionApplicantAndApplication,
        @WebParam(partName = "attachmentContent", name = "attachmentContent")
        byte[] attachmentContent
    );
}
