
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.tieto.p8.subvention.filenet.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-25T12:36:28.186+01:00
 * Generated source version: 3.4.2
 *
 */

@javax.jws.WebService(
                      serviceName = "SubventionService",
                      portName = "SubventionServicePort",
                      targetNamespace = "http://service.filenet.subvention.p8.tieto.com",
                      wsdlLocation = "file:subventionService.wsdl",
                      endpointInterface = "com.tieto.p8.subvention.filenet.service.SubventionService")

public class SubventionServicePortImpl implements SubventionService {

    private static final Logger LOG = Logger.getLogger(SubventionServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.tieto.p8.subvention.filenet.service.SubventionService#getApplicant(java.lang.String ytunnus, java.lang.String reknro, java.lang.String hetu)*
     */
    public com.tieto.p8.subvention.filenet.service.ContactInformationDTO getApplicant(java.lang.String ytunnus, java.lang.String reknro, java.lang.String hetu) {
        LOG.info("Executing operation getApplicant");
        System.out.println(ytunnus);
        System.out.println(reknro);
        System.out.println(hetu);
        try {
            com.tieto.p8.subvention.filenet.service.ContactInformationDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.tieto.p8.subvention.filenet.service.SubventionService#saveApplication(com.tieto.p8.subvention.filenet.service.Subvention subventionApplicantAndApplication, byte[] attachmentContent)*
     */
    public com.tieto.p8.subvention.filenet.service.ResultOfService saveApplication(Subvention subventionApplicantAndApplication, byte[] attachmentContent) {
        LOG.info("Executing operation saveApplication");
        System.out.println(subventionApplicantAndApplication);
        System.out.println(attachmentContent);
        try {
            com.tieto.p8.subvention.filenet.service.ResultOfService _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
