
package com.ibm.odsservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-25T12:46:50.924+01:00
 * Generated source version: 3.4.2
 *
 */

public class ODSServicePort_ODSService_Server{

    protected ODSServicePort_ODSService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ODSServiceImpl();
        String address = "http://localhost:80/CoHODSServices/services/ODSService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ODSServicePort_ODSService_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
