package com.ibm.odsservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-25T13:37:37.937+01:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "ODSServiceService",
                  wsdlLocation = "file:src/main/resources/wsdl/ODSService.wsdl",
                  targetNamespace = "http://odsservice.ibm.com")
public class ODSServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://odsservice.ibm.com", "ODSServiceService");
    public final static QName ODSService = new QName("http://odsservice.ibm.com", "ODSService");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/wsdl/ODSService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ODSServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/wsdl/ODSService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ODSServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ODSServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ODSServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ODSServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ODSServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ODSServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ODSServicePort
     */
    @WebEndpoint(name = "ODSService")
    public ODSServicePort getODSService() {
        return super.getPort(ODSService, ODSServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ODSServicePort
     */
    @WebEndpoint(name = "ODSService")
    public ODSServicePort getODSService(WebServiceFeature... features) {
        return super.getPort(ODSService, ODSServicePort.class, features);
    }

}
