
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ibm.odsservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-25T13:37:37.899+01:00
 * Generated source version: 3.4.2
 *
 */

@javax.jws.WebService(
                      serviceName = "ODSServiceService",
                      portName = "ODSService",
                      targetNamespace = "http://odsservice.ibm.com",
                      wsdlLocation = "file:src/main/resources/wsdl/ODSService.wsdl",
                      endpointInterface = "com.ibm.odsservice.ODSServicePort")

public class ODSServiceImpl implements ODSServicePort {

    private static final Logger LOG = Logger.getLogger(ODSServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ibm.odsservice.ODSServicePort#updateCitizenCaseStatus(java.lang.String accessUserId, java.lang.String caseId, java.lang.String citizenCaseStatus, java.lang.String eventType, java.lang.String eventCode, java.lang.String eventSource, java.lang.String eventDescription, java.lang.String eventDescriptionEN, java.lang.String eventDescriptionSV, javax.xml.datatype.XMLGregorianCalendar timeUpdated, javax.xml.datatype.XMLGregorianCalendar timeCreated)*
     */
    public int updateCitizenCaseStatus(java.lang.String accessUserId, java.lang.String caseId, java.lang.String citizenCaseStatus, java.lang.String eventType, java.lang.String eventCode, java.lang.String eventSource, java.lang.String eventDescription, java.lang.String eventDescriptionEN, java.lang.String eventDescriptionSV, javax.xml.datatype.XMLGregorianCalendar timeUpdated, javax.xml.datatype.XMLGregorianCalendar timeCreated) {
        LOG.info("Executing operation updateCitizenCaseStatus");
        System.out.println(accessUserId);
        System.out.println(caseId);
        System.out.println(citizenCaseStatus);
        System.out.println(eventType);
        System.out.println(eventCode);
        System.out.println(eventSource);
        System.out.println(eventDescription);
        System.out.println(eventDescriptionEN);
        System.out.println(eventDescriptionSV);
        System.out.println(timeUpdated);
        System.out.println(timeCreated);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
